version: "4.2"
services:
  postgres:
    image: postgres
    restart: on-failure
    container_name: orders-service
    environment:
      POSTGRES_DB: "orderdb"
      POSTGRES_USER: "wb"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5040:5432"
      
  nats-streaming:
    image: nats-streaming
    restart: no
    container_name: nats-stream
    ports:
      - 4222:4222