db:
  host:     "localhost"
  port:     "5040"
  username: "wb"
  password: "password"
  dbname:   "orderdb"
  sslmode:  "disable"

http_server:
  address: "localhost:8080"
  timeout: 4s
  ctx_timeout: 60s
  idle_timeout: 60s

stan: 
  stan_cluster_id: "test-cluster"
  cleint_id: "publisher"

